services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krt-ai-platform-web
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    env_file:
      - .env.production.local
    environment:
      - NODE_ENV=production
