-- RequestStatus values must be committed before a later migration can use
-- them as defaults (PostgreSQL error 55P04 otherwise).
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'QUEUED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PROVIDER_PENDING';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'RESULT_READY';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PERSISTING';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'RETRY_WAIT';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'RECONCILING';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'CANCEL_REQUESTED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
