import { z } from "zod";
import type { Prisma } from "@prisma/client";
import { requireAdminResponse } from "@/lib/admin-access";
import { db } from "@/lib/db";
import { internalError } from "@/lib/http";

const schema = z.object({ title: z.string().trim().max(180).optional(), sortOrder: z.number().int().min(0).max(9999).optional(), theme: z.string().trim().max(32).optional(), payload: z.record(z.string(), z.unknown()).optional(), publishStatus: z.enum(["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"]).optional(), restoreVersion: z.number().int().min(1).optional() });
const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
export async function PATCH(request: Request, { params }: { params: Promise<{ pageId: string; sectionId: string }> }) { const access = await requireAdminResponse(); if ("response" in access) return access.response; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: "区块信息无效。" }, { status: 400 }); const { pageId, sectionId } = await params; try { const section = await db.$transaction(async (tx) => { const current = await tx.pageSection.findFirst({ where: { id: sectionId, pageId }, include: { revisions: { orderBy: { version: "desc" }, take: 1 } } }); if (!current) throw new Error("SECTION_NOT_FOUND"); const restored = parsed.data.restoreVersion ? await tx.contentRevision.findFirst({ where: { sectionId, version: parsed.data.restoreVersion }, select: { payload: true } }) : null; if (parsed.data.restoreVersion && !restored) throw new Error("REVISION_NOT_FOUND"); const nextPayload = restored?.payload ?? (parsed.data.payload ? json(parsed.data.payload) : current.payload); const nextVersion = (current.revisions[0]?.version ?? 0) + 1; await tx.contentRevision.create({ data: { sectionId, version: nextVersion, payload: nextPayload as Prisma.InputJsonValue, createdBy: access.account.id } }); const updated = await tx.pageSection.update({ where: { id: sectionId }, data: { title: parsed.data.title, sortOrder: parsed.data.sortOrder, theme: parsed.data.theme, publishStatus: parsed.data.publishStatus, payload: nextPayload as Prisma.InputJsonValue } }); await tx.auditLog.create({ data: { actorId: access.account.id, action: parsed.data.restoreVersion ? "PAGE_SECTION_RESTORED" : "PAGE_SECTION_UPDATED", targetType: "PAGE_SECTION", targetId: sectionId, result: "SUCCEEDED", after: json({ ...parsed.data, version: nextVersion }) } }); return updated; }); return Response.json({ section }); } catch (error) { if (error instanceof Error && ["SECTION_NOT_FOUND", "REVISION_NOT_FOUND"].includes(error.message)) return Response.json({ error: "页面区块或历史版本不存在。" }, { status: 404 }); return internalError(); } }
