import { z } from "zod";
import { requireAdminResponse } from "@/lib/admin-access";
import { db } from "@/lib/db";
import { internalError } from "@/lib/http";

const schema = z.object({ slotKey: z.string().trim().toLowerCase().regex(/^[a-z0-9-]{2,120}$/), title: z.string().trim().min(1).max(180), description: z.string().trim().max(2_000).optional(), aspectRatio: z.string().trim().max(32).optional(), assetId: z.string().trim().max(120).optional(), mobileAssetId: z.string().trim().max(120).optional(), focalPoint: z.string().trim().max(64).optional(), status: z.enum(["PLACEHOLDER", "HIDDEN", "PUBLISHED"]).default("PLACEHOLDER") });
async function verifyAsset(id: string | undefined) { return !id || Boolean(await db.mediaAsset.findFirst({ where: { id, status: "ACTIVE" }, select: { id: true } })); }
export async function GET() { const access = await requireAdminResponse(); if ("response" in access) return access.response; try { return Response.json({ slots: await db.mediaSlot.findMany({ orderBy: { slotKey: "asc" } }) }); } catch { return internalError(); } }
export async function POST(request: Request) { const access = await requireAdminResponse(); if ("response" in access) return access.response; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: "媒体位信息无效。" }, { status: 400 }); const input = parsed.data; if (!(await verifyAsset(input.assetId)) || !(await verifyAsset(input.mobileAssetId))) return Response.json({ error: "绑定的媒体资源不存在或未启用。" }, { status: 400 }); if (input.status === "PUBLISHED" && !input.assetId) return Response.json({ error: "发布媒体位前需要绑定桌面端媒体资源。" }, { status: 400 }); try { const slot = await db.$transaction(async (tx) => { const created = await tx.mediaSlot.create({ data: input }); await tx.auditLog.create({ data: { actorId: access.account.id, action: "MEDIA_SLOT_CREATED", targetType: "MEDIA_SLOT", targetId: created.id, result: "SUCCEEDED", after: input } }); return created; }); return Response.json({ slot }, { status: 201 }); } catch { return internalError(); } }
