"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Slot = { id: string; slotKey: string; title: string; description: string | null; aspectRatio: string | null; assetId: string | null; mobileAssetId: string | null; focalPoint: string | null; status: "PLACEHOLDER" | "HIDDEN" | "PUBLISHED" };
export function AdminMediaSlotsPage() {
  const [slots, setSlots] = useState<Slot[]>([]); const [selectedId, setSelectedId] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const selected = slots.find((slot) => slot.id === selectedId);
  async function load() { const response = await fetch("/api/admin/media-slots"); const data = await response.json().catch(() => null); if (!response.ok) { setError(data?.error ?? "加载媒体位失败。"); return; } setSlots(data.slots ?? []); }
  useEffect(() => { const initialLoad = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(initialLoad); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); const endpoint = selected ? `/api/admin/media-slots/${selected.id}` : "/api/admin/media-slots"; const response = await fetch(endpoint, { method: selected ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setError(data?.error ?? "保存媒体位失败。"); return; } setMessage(selected ? "媒体位已更新。" : "媒体位已创建。绑定媒体后可发布。 "); setSelectedId(data.slot?.id ?? selectedId); await load(); }
  return <main className="admin-cms"><div className="admin-cms-top"><div><Link href="/admin" className="back-link">← 运营后台</Link><span className="eyebrow dark">MEDIA SLOTS</span><h1>页面媒体位</h1><p>将已上传媒体绑定到固定页面位置。发布后前台立即读取；下线或隐藏后自动回退到品牌占位，不会留下破图。</p></div></div>{error && <p className="admin-message admin-error">{error}</p>}{message && <p className="admin-message admin-success">{message}</p>}<section className="admin-cms-grid"><form className="admin-cms-form" key={selected?.id ?? "new"} onSubmit={save}><h2>{selected ? `编辑：${selected.title}` : "新建媒体位"}</h2>{selected ? <><label>媒体位 Key<input value={selected.slotKey} readOnly /></label><button type="button" className="admin-section-edit" onClick={() => setSelectedId("")}>新建媒体位</button></> : <label>媒体位 Key<input name="slotKey" required pattern="[a-z0-9-]+" placeholder="例如 home-hero" /></label>}<label>标题<input name="title" required defaultValue={selected?.title} /></label><label>说明<textarea name="description" defaultValue={selected?.description ?? ""} /></label><label>推荐比例<input name="aspectRatio" defaultValue={selected?.aspectRatio ?? "16:9"} placeholder="例如 16:9" /></label><label>桌面端媒体资源 ID<input name="assetId" defaultValue={selected?.assetId ?? ""} placeholder="从媒体库复制" /></label><label>移动端媒体资源 ID（可选）<input name="mobileAssetId" defaultValue={selected?.mobileAssetId ?? ""} placeholder="可使用单独竖版资源" /></label><label>裁切焦点（可选）<input name="focalPoint" defaultValue={selected?.focalPoint ?? "center"} placeholder="例如 50% 35%" /></label><label>状态<select name="status" defaultValue={selected?.status ?? "PLACEHOLDER"}><option value="PLACEHOLDER">显示品牌占位</option><option value="HIDDEN">隐藏媒体</option><option value="PUBLISHED">发布绑定媒体</option></select></label><Link className="admin-form-note" href="/admin/media">打开图片与视频媒体库 →</Link><button className="button button-lime" disabled={busy}>{busy ? "保存中…" : selected ? "保存媒体位" : "创建媒体位"}</button></form><div><h2 className="admin-list-title">现有媒体位</h2><div className="admin-list">{slots.map((slot) => <article key={slot.id}><span>{slot.status} · {slot.aspectRatio || "未设比例"}</span><strong>{slot.title}</strong><small>{slot.slotKey}</small><small>桌面端：{slot.assetId || "未绑定"} · 移动端：{slot.mobileAssetId || "沿用桌面端"}</small><div className="admin-list-actions"><button type="button" onClick={() => setSelectedId(slot.id)}>编辑</button></div></article>)}{!slots.length && <p className="admin-empty">暂无媒体位，或当前数据库尚未连接。</p>}</div></div></section></main>;
}
