"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Announcement = { id: string; title: string; content: string; publishStatus: string; publishAt: string | null; sortOrder: number; updatedAt: string };
function localDate(value: string | null) { return value ? new Date(value).toISOString().slice(0, 16) : ""; }

export function AdminCourseAnnouncementsPage({ courseId }: { courseId: string }) {
  const [items, setItems] = useState<Announcement[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/admin/courses/${courseId}/announcements`); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "公告加载失败。"); setItems(body.announcements ?? []); }, [courseId]);
  useEffect(() => { void load().catch((reason) => setError(reason instanceof Error ? reason.message : "公告加载失败。")); }, [load]);
  async function submit(event: React.FormEvent<HTMLFormElement>, item?: Announcement) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); const raw = Object.fromEntries(new FormData(event.currentTarget).entries()); const payload = { title: raw.title, content: raw.content, publishStatus: raw.publishStatus, publishAt: raw.publishAt ? new Date(String(raw.publishAt)).toISOString() : null, sortOrder: Number(raw.sortOrder || 0) }; try { const response = await fetch(item ? `/api/admin/courses/${courseId}/announcements/${item.id}` : `/api/admin/courses/${courseId}/announcements`, { method: item ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "公告保存失败。"); event.currentTarget.reset(); setNotice(item ? "公告已更新并写入审计。" : "公告已创建并写入审计。"); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "公告保存失败。"); } finally { setBusy(false); } }
  return <main className="admin-cms"><div className="admin-cms-top"><div><Link href={`/admin/courses/${courseId}`} className="back-link">← 返回课程</Link><span className="eyebrow dark">COURSE ANNOUNCEMENTS</span><h1>课程公告</h1><p>只有报名有效的学员才能看到已发布且已到发布时间的公告。</p></div></div>{error && <p className="admin-message admin-error">{error}</p>}{notice && <p className="admin-message admin-success">{notice}</p>}<section className="admin-curriculum-layout"><form className="admin-cms-form" onSubmit={(event) => void submit(event)}><h2>新增公告</h2><AnnouncementFields /><button className="button button-lime" disabled={busy}>创建公告</button></form><div className="admin-cms-list">{items.map((item) => <form className="admin-cms-form" key={item.id} onSubmit={(event) => void submit(event, item)}><h2>{item.title}</h2><AnnouncementFields item={item} /><button className="button button-outline-dark" disabled={busy}>保存公告</button></form>)}{!items.length && <p className="admin-empty">尚未创建公告。</p>}</div></section></main>;
}
function AnnouncementFields({ item }: { item?: Announcement }) { return <><label>标题<input name="title" required maxLength={180} defaultValue={item?.title ?? ""} /></label><label>正文<textarea name="content" required maxLength={20_000} defaultValue={item?.content ?? ""} /></label><div className="admin-form-grid"><label>状态<select name="publishStatus" defaultValue={item?.publishStatus ?? "DRAFT"}><option value="DRAFT">草稿</option><option value="REVIEW">待审核</option><option value="PUBLISHED">发布</option><option value="ARCHIVED">下线</option></select></label><label>定时发布（可选）<input name="publishAt" type="datetime-local" defaultValue={localDate(item?.publishAt ?? null)} /></label><label>排序<input name="sortOrder" type="number" min="0" max="9999" defaultValue={item?.sortOrder ?? 0} /></label></div></>; }
