"use client";
import {useState,useRef} from "react";
import Link from "next/link";
import Image from "next/image";
import {MessageCircle,Sparkles,Scale,Pencil,Send,ShieldCheck,LockKeyhole,UserRound,Lightbulb,Leaf,HeartHandshake,Music2,Palette,Code2,BookOpen,BrainCircuit,Box,Target,Presentation,ChevronLeft,ChevronRight,Phone,Play} from "lucide-react";
import {ToolBoard,ToolExample,ToolGrowth} from "./tool-visuals";
import s from "./reference-tools.module.css";
import { DEFAULT_TOOLS_CONTENT, type ToolsPageContent } from "@/lib/public-page-contract";
import type { PublicAiTool } from "@/lib/ai-tools";
import type { PublicMediaSlot } from "@/lib/site-media-slot";

function Asset({sheet="full",box,alt,className=""}:{sheet?:string;box:string;alt:string;className?:string}){const [x,y]=box.split(" ").map(Number),cls=`${s.asset} ${className}`;if(sheet==="tool-shelves")return <ToolBoard kind={y<180?"music":y<370?"art":y<550?"programming":"reading"} className={cls}/>;if(sheet==="gallery")return <ToolExample kind={x<330?"music":x<490?"art":x<640?"programming":"reading"} className={cls}/>;if(sheet==="work-growth")return <ToolGrowth index={[170,305,437,567,697].indexOf(x)} className={cls}/>;return <Image src="/media/reference-v4/hd/tools-hero-seamless.png" width={1536} height={1024} alt={alt} className={cls} priority/>}

const fallbackTools=[{toolKey:"music",name:"AI 音乐",slug:"ai-music",copy:<>用 AI 编曲、编写提示语，<br/>创作属于你的旋律与节奏。</>,box:"187 7 627 160",icon:Music2},{toolKey:"image",name:"AI 绘画",slug:"ai-art",copy:<>从草图到成图，AI 陪你<br/>探索风格、配色与细节。</>,box:"187 191 626 163",icon:Palette},{toolKey:"code",name:"AI 编程",slug:"ai-programming",copy:<>写代码、理逻辑、看结果，<br/>让想法在屏幕上运行起来。</>,box:"187 377 627 160",icon:Code2},{toolKey:"reading",name:"AI 阅读",slug:"ai-reading",copy:<>逐段读懂文章并生成对应画面，<br/>把阅读理解变成一册个人绘本。</>,box:"192 567 620 145",icon:BookOpen}];
const steps=[{title:"描述",copy:"明确目标与想法",icon:MessageCircle},{title:"生成",copy:"AI生成初版内容",icon:Sparkles},{title:"比较",copy:"多方案对比评估",icon:Scale},{title:"修改",copy:"优化细节与表达",icon:Pencil},{title:"表达",copy:"输出作品与分享",icon:Send}];
const growth=[{title:"灵感萌芽",copy:"一个模糊的想法",box:"170 66 96 47"},{title:"初版生成",copy:"AI生成第一版",box:"305 66 92 47"},{title:"优化迭代",copy:"调整内容与细节",box:"437 66 92 47"},{title:"整合完善",copy:"融入代码/声音/图像",box:"567 66 93 47"},{title:"最终作品",copy:"完成任务与展示",box:"697 66 96 47"}];
const courses=[{title:"编程基础与算法思维",href:"programming"},{title:"3D建模与数字设计",href:"3d-modeling"},{title:"机器人与智能硬件",href:"robotics"},{title:"科创项目与研究实践",href:"innovation"}];
const abilities=[{title:"跨学科融合应用",icon:BrainCircuit},{title:"问题解决与创新能力",icon:Target},{title:"工程实践与协作",icon:Box},{title:"作品集与展示表达",icon:Presentation}];
const responsibilities=[{title:"安全第一",copy:"保护个人信息安全",icon:ShieldCheck},{title:"隐私可控",copy:"你的数据你做主",icon:LockKeyhole},{title:"内容合规",copy:"文明创作，尊重他人",icon:UserRound},{title:"AI 为我所用",copy:"工具辅助，不替代思考",icon:Lightbulb},{title:"绿色友好",copy:"节能减碳，善用资源",icon:Leaf},{title:"共同成长",copy:"互助互学，共建社区",icon:HeartHandshake}];
const examples=[{title:"音乐作品",name:"《星航旋律》",type:"电子音乐",box:"189 11 138 68",slug:"ai-music"},{title:"科学插画",name:"《海洋微观世界》",type:"科普插画",box:"341 11 138 68",slug:"ai-art"},{title:"互动程序",name:"《小小探险家》",type:"Python 游戏",box:"494 11 137 68",slug:"ai-programming"},{title:"阅读思维导图",name:"《AI 探索教育》",type:"思维导图",box:"647 11 138 68",slug:"ai-reading"}];
export function ReferenceTools({ content = DEFAULT_TOOLS_CONTENT, contentState = "missing", publicTools, toolState = "unavailable", heroMedia, mediaState = "unavailable" }: { content?: ToolsPageContent; contentState?: "published" | "missing" | "draft" | "unavailable"; publicTools?: PublicAiTool[]; toolState?: "ready" | "unavailable"; heroMedia?: PublicMediaSlot; mediaState?: "ready" | "unavailable" }){const tools=publicTools===undefined?fallbackTools:publicTools.flatMap(tool=>{const visual=fallbackTools.find(item=>item.toolKey===tool.toolKey);return visual?[{...visual,name:tool.name,copy:tool.description,slug:tool.routePath.replace(/^\/tools\//,"")}]:[]});const [offset,setOffset]=useState(0);const dialog=useRef<HTMLDialogElement>(null);const [preview,setPreview]=useState<{title:string;sheet:string;box:string;slug:string}|null>(null);function openPreview(item:NonNullable<typeof preview>){setPreview(item);dialog.current?.showModal()}return <main className={s.page} data-content-state={contentState} data-tool-state={toolState} data-media-state={mediaState}>
  <section className={s.hero}>{heroMedia?<Image src={heroMedia.src} width={1536} height={1024} alt={heroMedia.altText} className={s.heroPhoto} priority/>:<Asset box="0 0 2000 1125" alt="三位少年使用平板、音乐键盘和机器人进行AI创作" className={s.heroPhoto}/>}<div className={s.heroCopy}><h1>{content.hero.titleLine1}<br/>{content.hero.titleLine2}</h1><p>{content.hero.descriptionLine1}<br/>{content.hero.descriptionLine2}</p><div><Link href="#creation-tools">立即开始创作</Link><Link href="/courses">了解课程体系</Link></div></div></section>
  <div className={s.content}>
    <section className={s.shelves} id="creation-tools" aria-label="四大AI创作工具">{tools.length===0&&<p role="status">当前没有对外开放的 AI 工具。</p>}{tools.map((tool,i)=><article className={s.shelf} key={tool.slug}><div className={s.toolCopy}><b>{String(i+1).padStart(2,"0")}</b><h2>{tool.name}</h2><p>{tool.copy}</p><Link href={`/tools/${tool.slug}`}>开始创作</Link></div><button className={s.demoPreview} aria-label={`放大查看${tool.name}创作流程`} onClick={()=>openPreview({title:tool.name+"创作流程",sheet:"tool-shelves",box:tool.box,slug:tool.slug})}><Asset sheet="tool-shelves" box={tool.box} alt={`${tool.name}创作流程与示例作品展示`}/></button></article>)}</section>
    <section className={`${s.strip} ${s.steps}`}><h2>创作五步</h2><div>{steps.map(({title,copy,icon:Icon},i)=><article key={title}><Icon/><h3>{title}</h3><p>{copy}</p>{i<4&&<span>→</span>}</article>)}</div></section>
    <section className={`${s.strip} ${s.growth}`}><h2>一件作品<br/>如何成长</h2><div>{growth.map((g,i)=><article key={g.title}><span className={s.dot}/><h3>{g.title}</h3><p>{g.copy}</p><Asset sheet="work-growth" box={g.box} alt={`${g.title}阶段作品`}/>{i<4&&<span className={s.growthArrow}>→</span>}</article>)}</div></section>
    <section className={`${s.strip} ${s.connections}`}><h2>工具与课程<br/>如何连接</h2><div className={s.connectionGrid}><svg viewBox="0 0 1000 137" preserveAspectRatio="none" aria-hidden="true"><g fill="none" strokeWidth=".8">{["#fa9b7a","#687ffa","#74b878","#edb45e"].map((color,i)=><g stroke={color} key={color}><path d={`M200 ${35+i*28}C255 ${35+i*28},255 ${35+((i+1)%4)*28},310 ${35+((i+1)%4)*28}`}/><path d={`M590 ${35+i*28}C645 ${35+i*28},645 ${35+((i+2)%4)*28},700 ${35+((i+2)%4)*28}`}/></g>)}</g></svg><div><h3>AI 工具</h3>{tools.map(({name,slug,icon:Icon})=><Link href={`/tools/${slug}`} key={slug}><Icon/>{name}</Link>)}</div><div><h3>课程方向</h3>{courses.map(c=><Link href={`/courses/directions/${c.href}`} key={c.href}>{c.title}</Link>)}</div><div><h3>能力收获</h3>{abilities.map(({title,icon:Icon})=><p key={title}><Icon/>{title}</p>)}</div></div></section>
    <section className={`${s.strip} ${s.responsibilities}`}><h2>负责任的 AI<br/>与隐私保护</h2><div>{responsibilities.map(({title,copy,icon:Icon})=><article key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className={`${s.strip} ${s.gallery}`}><h2>大家的作品</h2><button className={s.previous} aria-label="上一组示例作品" onClick={()=>setOffset((offset+3)%4)}><ChevronLeft/></button><div aria-live="polite">{examples.map((_,i)=>{const e=examples[(i+offset)%examples.length];return <button className={s.example} onClick={()=>openPreview({title:e.name,sheet:"gallery",box:e.box,slug:e.slug})} key={e.slug}><figure><Asset sheet="gallery" box={e.box} alt={e.name}/>{(e.slug==="ai-music"||e.slug==="ai-art")&&<Play className={s.play}/>}</figure><h3>{e.title}</h3><strong>{e.name}</strong><p>{e.type}</p></button>})}</div><button className={s.next} aria-label="下一组示例作品" onClick={()=>setOffset((offset+1)%4)}><ChevronRight/></button></section>
    <section className={s.cta}><div><h2>想把想法变成作品？</h2><p>预约免费体验课，开启你的 AI 创作之旅！</p></div><Link href="/consult">立即咨询</Link><a href="tel:19921536568"><Phone/>19921536568</a></section>
  </div><dialog ref={dialog} className={s.previewDialog}><div className={s.previewHeader}><h2>{preview?.title}</h2><button onClick={()=>dialog.current?.close()} aria-label="关闭示例预览">关闭 ×</button></div>{preview&&<><p>创作示例 · 可横向查看完整细节</p><div className={s.previewCanvas}><Asset sheet={preview.sheet} box={preview.box} alt={preview.title}/></div><Link href={`/tools/${preview.slug}`}>进入工具，开始自己的创作 →</Link></>}</dialog></main>}
