"use client";
import {useRef,useState} from "react";
import {Check,FileText,FolderOpen,Network,PenLine,Save,Sparkles,Trash2,Upload} from "lucide-react";
import s from "./reference-reading.module.css";

const sample="骆驼祥子第一次拉车时，怀着对新生活的期待。他勤劳、要强，相信只要努力就能拥有自己的车。清晨出车，路况、乘客与收入都成为他生活的一部分。";
const outline=["1. 开端：祥子的背景","2. 发展：买车的决心","　2.1 攒钱的目标","　2.2 生活的压力","3. 高潮：第一次拉车","　3.1 清晨出车","　3.2 拉车过程","　3.3 内心感受","4. 结尾：对未来的希望"];
function MindMap(){return <svg className={s.mind} viewBox="0 0 680 270" role="img" aria-label="第一次拉车关键词网络"><g fill="none" stroke="#5e8ee5" strokeWidth="2"><path d="M340 135H250l-30-65H130M250 135l-30 65H130M340 135H435l28-65h80M435 135l28 65h80"/>{[[130,70],[130,200],[543,70],[543,200]].map(([x,y],i)=><path key={i} d={`M${x} ${y}h-50l-22-20M80 ${y}H55M${x} ${y}h-50l-22 20M543 ${y}h50l22-20M593 ${y}h28M543 ${y}h50l22 20`}/>)}</g><g fill="#eef4ff" stroke="#5e8ee5">{[[340,135,95,42],[180,70,85,35],[180,200,85,35],[500,70,95,35],[500,200,95,35]].map(([x,y,w,h],i)=><rect key={i} x={x-w/2} y={y-h/2} width={w} height={h} rx="18"/>)}</g><g textAnchor="middle" fontFamily="Microsoft YaHei" fill="#1748a9" fontSize="16" fontWeight="600"><text x="340" y="141">第一次拉车</text><text x="180" y="76">祥子</text><text x="180" y="206">车厂</text><text x="500" y="76">清晨出车</text><text x="500" y="206">内心感受</text></g></svg>}

export function ReferenceReading(){
 const [title,setTitle]=useState("《骆驼祥子》节选：第一次拉车"),[text,setText]=useState(sample),[checks,setChecks]=useState([true,true,true,false]),[tab,setTab]=useState("阅读结果"),[note,setNote]=useState(""),[status,setStatus]=useState("");const file=useRef<HTMLInputElement>(null);
 function importFile(f?:File){if(!f)return;if(f.size>10*1024*1024){setStatus("文件超过 10MB，请选择较小的文本文件。");return}if(f.type.startsWith("text/")||/\.(txt|md)$/i.test(f.name)){const reader=new FileReader();reader.onload=()=>{setText(String(reader.result));setTitle(f.name.replace(/\.[^.]+$/,"")||title);setStatus("文本已导入，可以开始分析。");};reader.readAsText(f)}else setStatus("DOCX 已选择；当前演示请粘贴正文以保证内容读取准确。")}
 return <main className={s.page} aria-label="AI阅读助手"><div className={s.workspace}><section className={s.input}><header><h1>1. 输入阅读材料</h1><button onClick={()=>{setText("");setStatus("")}}><Trash2/>清空内容</button></header><label>文章标题 <span>（可编辑）</span><div className={s.titleInput}><input value={title} maxLength={80} onChange={e=>setTitle(e.target.value)}/><small>{title.length} / 80</small></div></label><label>粘贴或导入文本</label><div className={s.drop} onClick={()=>file.current?.click()}><Upload/><strong>粘贴文本到这里</strong><span>或点击下方按钮导入文件</span><small>支持 .txt / .md / .docx 格式、文件 ≤10MB</small><div>{[".txt",".md",".docx"].map(x=><button key={x} onClick={e=>{e.stopPropagation();file.current?.click()}}><FileText/>上传 {x}</button>)}</div></div><input hidden ref={file} type="file" accept=".txt,.md,.docx,text/plain,text/markdown" onChange={e=>importFile(e.target.files?.[0])}/><label>教师引导 <span>（可选）</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={300} placeholder="请输入本次阅读的目标、背景信息或关注重点，帮助AI更好地分析学生阅读。"/></label><fieldset><legend>分析重点 <span>（可多选）</span></legend><div className={s.checks}>{["文章结构","关键词","理解问题","表达练习"].map((x,i)=><button key={x} aria-pressed={checks[i]} onClick={()=>setChecks(checks.map((v,n)=>n===i?!v:v))}><span>{checks[i]&&<Check/>}</span>{x}</button>)}</div></fieldset><button className={s.analyze} disabled={!text.trim()} onClick={()=>setStatus("分析完成：已生成文章结构、关键词网络和循证问题。") }><Sparkles/>开始智能分析</button>{status&&<p className={s.status}>{status}</p>}</section>
 <section className={s.output}><div className={s.tabs}>{["阅读结果","历史记录"].map(x=><button key={x} className={tab===x?s.active:""} onClick={()=>setTab(x)}>{x}</button>)}</div>{tab==="历史记录"?<div className={s.empty}><FolderOpen/><h2>本地阅读记录</h2><p>当前示例尚未保存完整阅读记录。</p></div>:<><div className={s.analysis}><aside><h2>文章结构</h2>{outline.map((x,i)=><button className={i===0?s.selected:i===4?s.orange:""} key={x}>{x}</button>)}</aside><div className={s.overview}><h2>文章概览</h2><p>本文通过祥子第一次拉车的经历，展现了他勤劳、要强、对未来充满希望的性格特点，也反映了旧社会底层人物谋生的艰辛。</p><dl><div><dt>体裁：</dt><dd>小说节选</dd></div><div><dt>字数：</dt><dd>约1,256字</dd></div><div><dt>难度：</dt><dd>中等</dd></div><div><dt>适读年级：</dt><dd>初中</dd></div></dl><h2>关键词网络</h2><MindMap/></div></div><section className={s.questions}><h2>理解问题 <span>（证据链接）</span></h2>{[["祥子为什么对第一次拉车充满期待？","第3段“他觉得拉车是自己的事，自己的路。”"],["作者描写清晨出车时的环境，有什么作用？","第5段“天还没亮，街上静悄悄的，只有车轮的声音。”"],["从哪些细节可以看出祥子是一个要强的人？","第8段“他不愿意多要钱，也不肯白跑一趟。”"]].map((q,i)=><div key={i}><b>{i+1}.　{q[0]}</b><span>证据：{q[1]}</span><em>已找到证据 <Check/></em></div>)}</section><div className={s.bottom}><section><h2>表达练习</h2><p>请选择一个角度，写一段不少于150字的片段描写。</p><ul><li>角度一：祥子第一次拉车回家的心情</li><li>角度二：从旁观者的视角看祥子拉车</li><li>角度三：如果你是祥子的朋友，你会对他说什么？</li></ul><button><PenLine/>开始写作</button></section><section><h2>教师备注</h2><textarea placeholder="在此记录课堂观察、学生难点或下一步教学建议..."/><button onClick={()=>setStatus("教师备注已保存在当前浏览器。") }><Save/>保存备注</button></section></div></>}</section></div><section className={s.process}>{[{icon:FileText,title:"导入文本",copy:"粘贴或上传阅读材料"},{icon:Network,title:"识别结构",copy:"AI 分析文章结构与要点"},{icon:Sparkles,title:"追踪证据",copy:"定位关键证据，支持理解"},{icon:PenLine,title:"形成表达",copy:"练习表达，输出观点"}].map(({icon:Icon,title,copy},i)=><article key={title}><b>{i+1}</b><Icon/><div><h2>{title}</h2><p>{copy}</p></div>{i<3&&<span>➜</span>}</article>)}</section></main>
}
