import { z } from "zod";
import { requireAdminResponse } from "@/lib/admin-access";
import { isMediaContentType } from "@/lib/content-media";
import { db } from "@/lib/db";
import { internalError } from "@/lib/http";

const schema = z.object({ assetId: z.string().min(1).max(120), caption: z.string().trim().max(500).optional(), focalPoint: z.string().trim().max(64).optional(), sortOrder: z.number().int().min(0).max(9999).default(0), isCover: z.boolean().default(false) });
export async function GET(_request: Request, { params }: { params: Promise<{ contentType: string; itemId: string }> }) { const access = await requireAdminResponse(); if ("response" in access) return access.response; const { contentType, itemId } = await params; if (!isMediaContentType(contentType)) return Response.json({ error: "内容类型不存在。" }, { status: 404 }); try { const entries = await db.contentMedia.findMany({ where: { contentType, contentId: itemId }, orderBy: [{ isCover: "desc" }, { sortOrder: "asc" }] }); const assets = entries.length ? await db.mediaAsset.findMany({ where: { id: { in: entries.map((entry) => entry.assetId) } }, select: { id: true, title: true, mimeType: true, status: true } }) : []; const assetsById = new Map(assets.map((asset) => [asset.id, asset])); return Response.json({ entries: entries.map((entry) => ({ ...entry, asset: assetsById.get(entry.assetId) ?? null })) }); } catch { return internalError(); } }
export async function POST(request: Request, { params }: { params: Promise<{ contentType: string; itemId: string }> }) { const access = await requireAdminResponse(); if ("response" in access) return access.response; const { contentType, itemId } = await params; if (!isMediaContentType(contentType)) return Response.json({ error: "内容类型不存在。" }, { status: 404 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: "媒体关联信息无效。" }, { status: 400 }); try { const entry = await db.$transaction(async (tx) => { const asset = await tx.mediaAsset.findFirst({ where: { id: parsed.data.assetId, status: "ACTIVE" }, select: { id: true } }); if (!asset) throw new Error("ASSET_NOT_FOUND"); if (parsed.data.isCover) await tx.contentMedia.updateMany({ where: { contentType, contentId: itemId }, data: { isCover: false } }); const created = await tx.contentMedia.create({ data: { contentType, contentId: itemId, ...parsed.data } }); await tx.auditLog.create({ data: { actorId: access.account.id, action: "CONTENT_MEDIA_ATTACHED", targetType: contentType.toUpperCase(), targetId: itemId, result: "SUCCEEDED", after: { mediaId: created.id, assetId: parsed.data.assetId } } }); return created; }); return Response.json({ entry }, { status: 201 }); } catch (error) { return error instanceof Error && error.message === "ASSET_NOT_FOUND" ? Response.json({ error: "媒体不存在或已下线。" }, { status: 400 }) : internalError(); } }
