import Link from "next/link";
import { AccountType } from "@prisma/client";
import { getCurrentAccount } from "@/lib/auth";
import { getLearningDashboardSummary, canUseLearningCenter } from "@/lib/learning";
import { isEnrollmentExpiring, learningContinueHref } from "@/lib/learning-dashboard-policy";

export default async function LearningDashboardPage() {
  const account = await getCurrentAccount().catch(() => null);
  if (!account) return <section className="workspace-card"><span className="eyebrow dark">MY LEARNING</span><h1>登录后开始学习</h1><p>课程、课件和学习进度只对已登录的个人学员展示。</p><Link className="button button-lime" href="/login?mode=personal">学员登录</Link></section>;
  if (account.type !== AccountType.PERSONAL || !canUseLearningCenter(account.type)) return <section className="workspace-card"><span className="eyebrow dark">MY LEARNING</span><h1>这是个人学员中心</h1><p>学校共享账号请进入课堂空间；管理员请从运营后台操作。</p><Link className="button button-lime" href="/">返回首页</Link></section>;
  const summary = await getLearningDashboardSummary(account.id).catch(() => null);
  const enrollments = summary?.enrollments ?? [];
  const expiring = enrollments.filter((enrollment) => isEnrollmentExpiring(enrollment.endsAt));
  const courseById = new Map(enrollments.map((enrollment) => [enrollment.courseId, enrollment]));
  return <section className="workspace-card"><div className="learning-heading"><div><span className="eyebrow dark">MY LEARNING</span><h1>继续我的学习</h1><p>课程、课件和课程内 AI 工具都从这里开始。</p></div><Link href="/courses" className="button button-outline-dark">浏览课程</Link></div>{enrollments.length ? <><div className="learning-course-grid">{enrollments.map((enrollment) => { const lessonIds = new Set(enrollment.course.modules.flatMap((module) => module.lessons.map((lesson) => lesson.id))); const href = learningContinueHref(enrollment.course.slug, enrollment.lastLessonId, lessonIds); return <Link href={href} className="learning-course-card" key={enrollment.id}><span>{enrollment.course.category.name} · {enrollment.progressPercent}%</span><h2>{enrollment.course.name}</h2><p>{enrollment.course.shortDescription}</p><div className="learning-progress"><i style={{ width: `${enrollment.progressPercent}%` }} /></div><b>继续学习 →</b></Link>; })}</div>{expiring.length > 0 && <section className="learning-summary-panel learning-expiring"><span>课程有效期提醒</span><h2>即将到期的课程</h2>{expiring.map((enrollment) => <Link key={enrollment.id} href={`/learn/courses/${enrollment.course.slug}`}>{enrollment.course.name}<b>{enrollment.endsAt?.toLocaleDateString("zh-CN")} 到期</b></Link>)}</section>}<div className="learning-summary-grid"><section className="learning-summary-panel"><span>RECENT COURSEWARE</span><h2>最近查看课件</h2>{summary?.recentCourseware.length ? summary.recentCourseware.map((access) => <Link key={access.id} href={`/learn/courseware/${access.asset.id}`}><strong>{access.asset.title}</strong><small>{access.asset.course.name} · {access.accessedAt.toLocaleString("zh-CN")}</small></Link>) : <p>你还没有查看过课件。</p>}</section><section className="learning-summary-panel"><span>COURSE TOOLS</span><h2>课程内 AI 工具</h2>{summary?.courseTools.length ? summary.courseTools.map((binding) => { const enrollment = courseById.get(binding.courseId); if (!enrollment) return null; const href = binding.lessonId ? `/learn/courses/${enrollment.course.slug}/lessons/${binding.lessonId}` : `/learn/courses/${enrollment.course.slug}`; return <Link key={`${binding.courseId}-${binding.toolKey}-${binding.lessonId ?? "course"}`} href={href}><strong>{binding.toolKey}</strong><small>{enrollment.course.name}{binding.lessonId ? " · 前往课时打开" : " · 查看课程入口"}</small></Link>; }) : <p>当前报名课程暂未配置 AI 工具。</p>}</section><section className="learning-summary-panel"><span>MY WORKS</span><h2>最近作品</h2>{summary?.recentWorks.length ? summary.recentWorks.map((work) => <Link key={work.id} href="/my-works"><strong>{work.title}</strong><small>{work.type} · {work.updatedAt.toLocaleDateString("zh-CN")}</small></Link>) : <p>完成一次创作后，作品会出现在这里。</p>}<Link className="learning-summary-action" href="/my-works">打开作品集 →</Link></section></div></> : <div className="empty-learning"><h2>尚未加入课程</h2><p>课程报名后会出现在这里，不会伪造学习进度。</p><Link href="/consult" className="button button-lime">咨询课程</Link></div>}</section>;
}
