export type CompetitionReference = {
  slug: string;
  name: string;
  shortName: string;
  season: string;
  audience: string;
  organizer: string;
  shortlist: "是" | "否" | "以当年通知为准";
  preparation: string;
  focus: string;
  sourcePage: number;
};

export const competitionReferences: CompetitionReference[] = [
  {
    slug: "mingri-keji-zhixing",
    name: "上海市百万青少年争创“明日科技之星”活动",
    shortName: "明日科技之星",
    season: "1—5月",
    audience: "小学至高中",
    organizer: "上海市团委等",
    shortlist: "是",
    preparation: "小学生准备集体照、视频作品；中学生准备申报表、研究报告与摘要。",
    focus: "把一个真实问题讲清楚，并用作品或研究说明自己的判断。",
    sourcePage: 55,
  },
  {
    slug: "chuangke-xinxing",
    name: "上海创客新星大赛",
    shortName: "创客新星",
    season: "3—6月",
    audience: "小学至高中",
    organizer: "上海市教委、上海市科技艺术教育中心、上海创客教育联盟",
    shortlist: "是",
    preparation: "报名表、视频、照片与成本列表。",
    focus: "用完整的制作过程说明创意如何成为可验证的作品。",
    sourcePage: 56,
  },
  {
    slug: "songqingling-famingjiang",
    name: "宋庆龄少年儿童发明奖",
    shortName: "宋庆龄发明奖",
    season: "2—8月",
    audience: "小学至高中",
    organizer: "中国宋庆龄基金会、中国发明协会",
    shortlist: "否",
    preparation: "申报表、摘要、文章与图片等。",
    focus: "从儿童视角发现问题，用发明成果回应生活需要。",
    sourcePage: 56,
  },
  {
    slug: "chuyingbei",
    name: "“雏鹰杯”红领巾科创达人挑战赛",
    shortName: "雏鹰杯",
    season: "9—12月",
    audience: "小学二年级至初中九年级",
    organizer: "上海市团委、上海市教委、上海市青少年活动中心等",
    shortlist: "是",
    preparation: "课题申报表、研究报告、查新或查重报告及成果情况照片。",
    focus: "围绕课题完成调查、验证、修订与成果表达。",
    sourcePage: 57,
  },
  {
    slug: "saifu-chuangzhibei",
    name: "“赛复创智杯”上海市青少年科技创意设计评选活动",
    shortName: "赛复创智杯",
    season: "4—7月",
    audience: "小学至高中",
    organizer: "浦东新区青少年活动中心等",
    shortlist: "是",
    preparation: "活动申报表、创意设计文稿、模型照片及相关报名材料。",
    focus: "把创意写成设计文稿，再用模型和过程照片完成论证。",
    sourcePage: 57,
  },
  {
    slug: "youth-ai-innovation",
    name: "青少年人工智能创新大赛",
    shortName: "人工智能创新大赛",
    season: "初赛通常在8月底，决赛通常在9月中下旬",
    audience: "小学至高中",
    organizer: "青年报社",
    shortlist: "以当年通知为准",
    preparation: "围绕算法、工程、逻辑与场景应用持续打磨项目记录。",
    focus: "手册记录的赛道包括智能机器人、低空科技应用协同创新、AI+应用创业实践。",
    sourcePage: 58,
  },
  {
    slug: "shanghai-future-engineer",
    name: "上海未来工程师大赛",
    shortName: "未来工程师",
    season: "各区初评、市级报名与决赛通常集中在10月",
    audience: "小学至高中",
    organizer: "上海市教育委员会指导，上海科普教育发展基金会、上海市科技艺术教育中心、徐汇区教育局联合主办",
    shortlist: "是",
    preparation: "按当年赛项完成工程方案、原型、测试记录和现场表达准备。",
    focus: "覆盖结构、建筑、机械、航天、软件工程等项目，强调工程实践。",
    sourcePage: 58,
  },
  {
    slug: "xinann-weiyu-cup",
    name: "上海市青少年机器人知识与实践比赛",
    shortName: "西南位育杯",
    season: "3—5月",
    audience: "小学至高中",
    organizer: "各区青少年活动中心（区赛）、上海市科技艺术教育中心（市赛）",
    shortlist: "是",
    preparation: "从规则理解、机器人基础知识与专项操作三个方向准备。",
    focus: "手册记录为1个规定项目与7个自选项目，重在知识与实践结合。",
    sourcePage: 59,
  },
  {
    slug: "wrc-youth",
    name: "世界机器人大赛青少年机器人设计与信息素养大赛",
    shortName: "WRC青少年赛",
    season: "8月",
    audience: "小学至高中",
    organizer: "中国电子学会",
    shortlist: "是",
    preparation: "依据当年赛项，从机器人设计或信息素养方向完成专项训练。",
    focus: "围绕机器人技术开发、设计应用、电子电路、物联网与编程等领域。",
    sourcePage: 59,
  },
  {
    slug: "yangtze-ai-olympic",
    name: "长三角青少年人工智能奥林匹克挑战赛",
    shortName: "AI奥林匹克",
    season: "9月底",
    audience: "长三角地区中小学生",
    organizer: "上海市教育委员会",
    shortlist: "是",
    preparation: "按算法擂台与无人驾驶两条主赛道选择方向，完成赛项训练。",
    focus: "手册记录的嘉年华包含直播间、新视界、云学堂、实验室、绘画、展示会、开发者、无限飞跃等展区。",
    sourcePage: 60,
  },
  {
    slug: "shangtu-cup",
    name: "未来之星—上图杯模型大赛",
    shortName: "上图杯",
    season: "9—11月线上申报与作品征集，12月竞赛活动",
    audience: "小学至高中",
    organizer: "上海市老科学技术工作者协会",
    shortlist: "是",
    preparation: "线上提交报名表、作品选题与构思，再按通知完成作品征集。",
    focus: "从模型选题、构思到成品，形成连续的制作档案。",
    sourcePage: 60,
  },
  {
    slug: "china-chip",
    name: "中国“芯”助力中国梦—全国青少年通讯科技创新大赛",
    shortName: "中国芯选拔赛",
    season: "手册记录的地区选拔集中在6月底",
    audience: "小学至高中",
    organizer: "浦东青少年健康科普促进中心",
    shortlist: "是",
    preparation: "以当年地区选拔和全国总决赛通知为准。",
    focus: "围绕通讯科技创新作品完成地区选拔与作品评审。",
    sourcePage: 60,
  },
  {
    slug: "national-youth-drone",
    name: "全国青少年无人机大赛",
    shortName: "EDE无人机大赛",
    season: "8月暑期",
    audience: "小学至高中",
    organizer: "中国航空学会",
    shortlist: "是",
    preparation: "按操控、编程、组合、虚拟、创意等赛项选择专项准备。",
    focus: "以飞行实践、程序控制、团队协作与安全规范为核心。",
    sourcePage: 61,
  },
  {
    slug: "fly-beijing",
    name: "“飞向北京·飞向太空”全国青少年航空航天模型教育竞赛活动",
    shortName: "飞北",
    season: "举办时间以当年通知为准",
    audience: "小学至高中",
    organizer: "国家体育总局航空无线电模型运动管理中心",
    shortlist: "以当年通知为准",
    preparation: "依据所选模型或无人机项目，完成制作、调试、操控与规则训练。",
    focus: "包含航空模型与无人机项目，并按项目设置不同组别。",
    sourcePage: 61,
  },
];

export function findCompetitionReference(slug: string) {
  return competitionReferences.find((item) => item.slug === slug);
}
