"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Entry = { id: string; assetId: string; caption: string | null; focalPoint: string | null; sortOrder: number; isCover: boolean; asset: { title: string | null; mimeType: string | null; status: string } | null };
const labels: Record<string, string> = { activities: "科创活动", achievements: "学员成长", teachers: "师资", campuses: "校区", partners: "合作学校" };
export function AdminContentMediaPage({ contentType, itemId }: { contentType: string; itemId: string }) {
  const [entries, setEntries] = useState<Entry[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const base = `/api/admin/content/${contentType}/${itemId}/media`;
  async function load() { const response = await fetch(base); const data = await response.json().catch(() => null); if (!response.ok) { setError(data?.error ?? "加载媒体失败。"); return; } setEntries(data.entries ?? []); }
  useEffect(() => { void load(); }, [base]);
  async function attach(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch(base, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, sortOrder: Number(data.sortOrder || 0), isCover: data.isCover === "on" }) }); const result = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setError(result?.error ?? "绑定媒体失败。"); return; } event.currentTarget.reset(); setMessage("媒体已关联到内容。"); await load(); }
  async function change(entry: Entry, data: Record<string, unknown>) { const response = await fetch(`${base}/${entry.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json().catch(() => null); if (!response.ok) { setError(result?.error ?? "更新失败。"); return; } setMessage("媒体编排已更新。"); await load(); }
  async function remove(entry: Entry) { if (!window.confirm("解除这个媒体关联吗？原始媒体不会被删除。")) return; const response = await fetch(`${base}/${entry.id}`, { method: "DELETE" }); if (!response.ok) { setError("解除关联失败。"); return; } setMessage("媒体关联已解除。"); await load(); }
  const label = labels[contentType] ?? "内容";
  return <main className="admin-cms"><div className="admin-cms-top"><div><Link href={`/admin/content/${contentType}`} className="back-link">← {label}管理</Link><span className="eyebrow dark">CONTENT GALLERY</span><h1>{label}媒体编排</h1><p>可绑定多张已启用媒体，设置封面、排序、说明与裁切焦点；解除关联不会删除原始媒体。</p></div></div>{error && <p className="admin-message admin-error">{error}</p>}{message && <p className="admin-message admin-success">{message}</p>}<section className="admin-cms-grid"><form className="admin-cms-form" onSubmit={attach}><h2>关联媒体</h2><label>媒体资源 ID<input name="assetId" required /></label><label>说明<textarea name="caption" maxLength={500} /></label><label>裁切焦点<input name="focalPoint" placeholder="例如 50% 35%" /></label><label>排序<input name="sortOrder" type="number" min="0" defaultValue="0" /></label><label><input name="isCover" type="checkbox" /> 设为封面</label><Link className="admin-form-note" href="/admin/media">打开媒体库复制资源 ID →</Link><button className="button button-lime" disabled={busy}>{busy ? "绑定中…" : "绑定媒体"}</button></form><div><h2 className="admin-list-title">已关联媒体</h2><div className="admin-list">{entries.map((entry) => <article key={entry.id}><span>{entry.isCover ? "封面" : "图集"} · 排序 {entry.sortOrder}</span><strong>{entry.asset?.title || entry.assetId}</strong><small>{entry.caption || "未填写说明"} · {entry.focalPoint || "默认裁切"}</small><div className="admin-list-actions"><button type="button" onClick={() => void change(entry, { isCover: true })}>设为封面</button><button type="button" onClick={() => void change(entry, { sortOrder: Math.max(0, entry.sortOrder - 1) })}>上移</button><button type="button" onClick={() => void change(entry, { sortOrder: entry.sortOrder + 1 })}>下移</button><button type="button" onClick={() => void remove(entry)}>解除关联</button></div></article>)}{!entries.length && <p className="admin-empty">尚未关联媒体。</p>}</div></div></section></main>;
}
