"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Category = { id: string; name: string };
type Course = { id: string; name: string; slug: string; categoryId: string; shortDescription: string; fullDescription?: string | null; targetAudience?: string | null; gradeRange?: string | null; difficulty?: string | null; deliveryModes: string[]; durationText?: string | null; enrollmentStatus: string; coverAssetId?: string | null; publishStatus: string };

export function AdminCourseEditor({ courseId }: { courseId: string }) {
  const [course, setCourse] = useState<Course | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setError(""); try { const [courseResponse, categoriesResponse] = await Promise.all([fetch(`/api/admin/courses/${courseId}`), fetch("/api/admin/course-categories")]); const courseData = await courseResponse.json().catch(() => null); const categoryData = await categoriesResponse.json().catch(() => null); if (!courseResponse.ok) throw new Error(courseData?.error ?? "课程加载失败。"); if (!categoriesResponse.ok) throw new Error(categoryData?.error ?? "课程分类加载失败。"); setCourse(courseData.course); setCategories(categoryData.categories ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "课程加载失败。"); } }
  useEffect(() => { void load(); }, [courseId]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); const deliveryModes = String(data.deliveryModes ?? "").split(/[,，\n]/).map((value) => value.trim()).filter(Boolean); try { const response = await fetch(`/api/admin/courses/${courseId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, deliveryModes }) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.issues?.join(" ") ?? result?.error ?? "保存失败。"); setCourse(result.course); setMessage("课程基础信息已更新。发布状态仍会经过服务端条件校验。"); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败。"); } finally { setBusy(false); } }
  if (!course && !error) return <main className="admin-cms"><p className="admin-empty">正在加载课程…</p></main>;
  return <main className="admin-cms"><div className="admin-cms-top"><div><Link href="/admin/courses" className="back-link">← 课程管理</Link><span className="eyebrow dark">COURSE SETTINGS</span><h1>{course?.name ?? "课程基础信息"}</h1><p>维护公开介绍、招生属性和封面。模块、课时和课程工具请在课程结构页面维护。</p></div><Link href="/admin/curriculum" className="button button-outline-dark">课程结构与工具绑定</Link></div>{error && <p className="admin-message admin-error">{error}</p>}{message && <p className="admin-message admin-success">{message}</p>}{course && <form className="admin-cms-form admin-course-editor" onSubmit={submit}><label>课程 Slug<input value={course.slug} readOnly aria-readonly="true" /></label><label>课程分类<select name="categoryId" defaultValue={course.categoryId} required>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>课程名称<input name="name" defaultValue={course.name} required maxLength={180} /></label><label>一句话介绍<textarea name="shortDescription" defaultValue={course.shortDescription} required maxLength={500} /></label><label>公开详细介绍<textarea name="fullDescription" defaultValue={course.fullDescription ?? ""} maxLength={20_000} /></label><label>适合人群与先修要求<input name="targetAudience" defaultValue={course.targetAudience ?? ""} maxLength={500} /></label><label>年龄/年级范围<input name="gradeRange" defaultValue={course.gradeRange ?? ""} maxLength={80} /></label><label>难度<select name="difficulty" defaultValue={course.difficulty ?? "基础"}><option>启蒙</option><option>基础</option><option>进阶</option><option>竞赛</option><option>项目制</option></select></label><label>授课方式<textarea name="deliveryModes" defaultValue={course.deliveryModes.join("，")} maxLength={300} /></label><label>课时/学习周期<input name="durationText" defaultValue={course.durationText ?? ""} maxLength={80} /></label><label>招生状态<select name="enrollmentStatus" defaultValue={course.enrollmentStatus}><option value="OPEN">招生中</option><option value="COMING_SOON">即将开课</option><option value="FULL">已满班</option><option value="CONSULT">欢迎咨询</option><option value="ARCHIVED">展示归档</option></select></label><label>课程封面媒体 ID<input name="coverAssetId" defaultValue={course.coverAssetId ?? ""} maxLength={128} /></label><label>发布状态<select name="publishStatus" defaultValue={course.publishStatus}><option>DRAFT</option><option>REVIEW</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><p className="admin-form-note">发布时服务端会检查适合人群、封面以及至少一个已发布模块；草稿模块和课时不会进入公开课程页面。</p><button className="button button-lime" disabled={busy}>{busy ? "保存中…" : "保存课程基础信息"}</button></form>}</main>;
}
