"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Category = { id: string; name: string; slug: string; description: string | null; sortOrder: number; status: "ACTIVE" | "ARCHIVED"; _count: { courses: number } };

export function AdminCourseCategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([]); const [editing, setEditing] = useState<Category | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/admin/course-categories"); const data = await response.json().catch(() => null); if (!response.ok) { setError(data?.error ?? "加载分类失败。"); return; } setCategories(data.categories ?? []); }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); const response = await fetch("/api/admin/course-categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, sortOrder: Number(values.sortOrder || 0) }) }); const data = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setError(data?.error ?? "创建分类失败。"); return; } form.reset(); setMessage("课程分类已创建，可立即在课程管理中选择。"); await load(); }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; setBusy(true); setError(""); setMessage(""); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch(`/api/admin/course-categories/${editing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: values.name, description: values.description || undefined, sortOrder: Number(values.sortOrder), status: values.status }) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error ?? "更新分类失败。"); setEditing(null); setMessage(`“${editing.name}”已更新并写入审计。`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "更新分类失败。"); } finally { setBusy(false); } }
  return <main className="admin-cms"><div className="admin-cms-top"><div><Link href="/admin" className="back-link">← 运营后台</Link><span className="eyebrow dark">CURRICULUM SETTINGS</span><h1>课程分类管理</h1><p>课程分类、名称、介绍与排序由后台维护。归档分类不会继续显示在公开课程筛选中。</p></div></div>{error && <p className="admin-message admin-error">{error}</p>}{message && <p className="admin-message admin-success">{message}</p>}<section className="admin-cms-grid"><form className="admin-cms-form" onSubmit={create}><h2>新增课程分类</h2><label>分类名称<input name="name" required maxLength={120} /></label><label>分类 Slug<input name="slug" required pattern="[a-z0-9-]+" placeholder="例如 regular" /></label><label>分类介绍<textarea name="description" maxLength={500} /></label><label>排序<input name="sortOrder" type="number" min="0" defaultValue="0" /></label><button className="button button-lime" disabled={busy}>{busy ? "保存中…" : "创建分类"}</button></form><div><h2 className="admin-list-title">现有分类</h2><div className="admin-list">{categories.map((category) => <article key={category.id}><span>{category.status} · {category._count.courses} 门课程 · 排序 {category.sortOrder}</span><strong>{category.name}</strong><small>{category.slug}{category.description ? ` · ${category.description}` : ""}</small><div className="admin-list-actions"><button type="button" onClick={() => setEditing(category)}>编辑</button></div></article>)}{!categories.length && <p className="admin-empty">暂无数据，或当前数据库尚未连接。</p>}</div></div></section>{editing && <section className="admin-cms"><form className="admin-cms-form admin-category-editor" onSubmit={update}><h2>编辑分类</h2><label>分类 Slug<input value={editing.slug} readOnly aria-readonly="true" /></label><label>分类名称<input name="name" defaultValue={editing.name} required maxLength={120} /></label><label>分类介绍<textarea name="description" defaultValue={editing.description ?? ""} maxLength={500} /></label><label>排序<input name="sortOrder" type="number" min="0" max="9999" defaultValue={editing.sortOrder} /></label><label>状态<select name="status" defaultValue={editing.status}><option value="ACTIVE">ACTIVE</option><option value="ARCHIVED">ARCHIVED</option></select></label><p className="admin-form-note">已有课程的分类不会物理删除；如需移除分类，请先迁移课程或归档分类。</p><button className="button button-lime" disabled={busy}>{busy ? "保存中…" : "保存分类"}</button></form></section>}</main>;
}
