"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type MediaAsset = { id: string; title: string | null; altText: string | null; sourceType: string; mimeType: string | null; licenseNote: string | null; status: string; createdAt: string };
export function AdminMediaPage() {
  const [assets, setAssets] = useState<MediaAsset[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/admin/media"); const data = await response.json().catch(() => null); if (!response.ok) { setError(data?.error ?? "加载媒体库失败。"); return; } setAssets(data.assets ?? []); }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); const response = await fetch("/api/admin/media", { method: "POST", body: new FormData(event.currentTarget) }); const data = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setError(data?.error ?? "上传失败。"); return; } event.currentTarget.reset(); setMessage(`已上传“${data.asset?.title ?? "媒体"}”。复制资源 ID 并绑定到相应内容即可发布。`); await load(); }
  return <main className="admin-cms"><div className="admin-cms-top"><div><Link href="/admin" className="back-link">← 运营后台</Link><span className="eyebrow dark">MEDIA LIBRARY</span><h1>图片媒体库</h1><p>上传的图片通过受控媒体地址对外展示；请填写替代文本和授权说明，不要将生成图标注为真实课堂、师资或获奖资料。</p></div></div>{error && <p className="admin-message admin-error">{error}</p>}{message && <p className="admin-message admin-success">{message}</p>}<section className="admin-cms-grid"><form className="admin-cms-form" onSubmit={submit}><h2>上传图片</h2><label>图片文件<input name="file" type="file" required accept="image/jpeg,image/png,image/webp,image/gif,image/avif" /></label><label>标题<input name="title" maxLength={180} /></label><label>替代文本<input name="altText" maxLength={300} placeholder="说明图片中有什么" /></label><label>来源<select name="sourceType" defaultValue="REAL"><option value="REAL">真实授权素材</option><option value="HANDBOOK">项目手册资料</option><option value="GENERATED">生成概念图</option><option value="PLACEHOLDER">品牌占位</option></select></label><label>授权/使用说明<textarea name="licenseNote" maxLength={2000} placeholder="来源、授权范围、到期日或待确认说明" /></label><button className="button button-lime" disabled={busy}>{busy ? "上传中…" : "上传到媒体库"}</button></form><div><h2 className="admin-list-title">最近上传</h2><div className="admin-list">{assets.map((asset) => <article key={asset.id}><span>{asset.sourceType} · {asset.status}</span><strong>{asset.title || "未命名图片"}</strong><small>资源 ID：{asset.id}</small><small>{asset.altText || "未填写替代文本"}</small>{asset.licenseNote && <small>授权：{asset.licenseNote}</small>}</article>)}{!assets.length && <p className="admin-empty">暂无媒体资源，或当前数据库尚未连接。</p>}</div></div></section></main>;
}
