import Image from "next/image";
import {Atom,BookOpen,CheckCircle2,MessagesSquare,Rocket,Wrench} from "lucide-react";
import s from "./reference-activities.module.css";
const events=[{name:"上海市百万青少年争创明日科技之星",start:1,end:5,period:"1—5月"},{name:"上海创客新星大赛",start:3,end:6,period:"3—6月"},{name:"宋庆龄少年儿童发明奖",start:2,end:8,period:"2—8月"},{name:"“雏鹰杯”红领巾科创达人挑战赛",start:9,end:12,period:"9—12月"},{name:"“赛复创智杯”青少年科技创意设计评选",start:4,end:7,period:"4—7月"},{name:"青少年人工智能创新大赛",start:8,end:9,period:"8—9月"},{name:"上海未来工程师大赛",start:10,end:10,period:"10月"}];
const eventPhotos=["competition-prep-v2.png","prototype-iteration-v2.png","team-collaboration-v2.png","public-presentation-v2.png","workshop-process-v1.png","prototype-testing-v1.png","competition-prep-v2.png"];
const practices=[{src:"prototype-testing-v1.png",t:"精密加工，提升工程能力"},{src:"team-collaboration-v2.png",t:"团队协作，迭代优化方案"},{src:"prototype-iteration-v2.png",t:"数据记录，验证与改进"},{src:"public-presentation-v2.png",t:"场景测试，真实环境验证"}];
export function ReferenceActivities(){return <main className={s.page}>
  <section className={s.hero}><Image src="/media/site-v3/activities/workshop-process-v1.png" alt="学生协作调试机器人" fill priority/><div><small>科瑞特 AI　·　科创活动</small><h1>让作品走出课堂，<br/>在真实任务中接受检验。</h1><p>从兴趣出发 · 以问题为导向 · 用创新解决问题</p></div></section>
  <section className={s.topGrid}><div><h2>不同学段，科创活动如何助力成长路径？</h2><div className={s.stages}>{[{i:Atom,t:"小学生",h:"培养好奇心与动手力",c:"以兴趣探索为主，通过趣味与动手实践，建立发现问题与表达想法的信心。"},{i:Wrench,t:"初中生",h:"提升研究力与解决力",c:"围绕真实问题开展探究，学习设计方案、收集证据与迭代。"},{i:Rocket,t:"高中生",h:"强化创新力与表达力",c:"关注社会需求和前沿，完成有深度的项目与现场表达。"}].map(({i:Icon,t,h,c})=><article key={t}><Icon/><h3>{t}</h3><strong>{h}</strong><p>{c}</p></article>)}</div></div><div><h2>全年科创活动地图 <span>（手册规划周期）</span></h2><div className={s.timeline}><header>{[1,2,3,4,5,6,7,8,9,10,11,12].map(x=><span key={x}>{x}月</span>)}</header>{events.map((event,i)=><div className={i%2?s.blue:""} style={{gridColumn:`${event.start} / ${event.end+2}`}} key={event.name}><b>{event.name}</b><em>{event.period}</em></div>)}</div></div></section>
  <section><h2>主流科创活动图鉴 <span>（7项）</span></h2><div className={s.events}>{events.map((event,i)=><article key={event.name}><Image src={`/media/site-v3/activities/${eventPhotos[i]}`} alt={event.name} width={750} height={494}/><h3>{event.name}</h3><p>面向青少年开展，围绕创新实践、工程设计与公开表达形成完整项目经历。</p><span>{event.period}　创新　实践　工程</span></article>)}</div></section>
  <section><h2>准备材料清单对照 <span>（建议清晰、真实、完整）</span></h2><div className={s.materials}><table><thead><tr><th>材料类别</th><th>内容要点</th><th>建议呈现形式</th><th>注意事项</th></tr></thead><tbody>{[["项目说明","项目背景、目标、方案、创新点与应用场景","图文文档 / PPT","语言简洁、逻辑清晰"],["研究报告","研究过程、方法、数据、结果与结论","结构化报告（含图表）","数据真实、来源清楚"],["照片 / 视频","过程记录、作品展示、测试与应用场景","高清照片 / 短视频","内容完整、重点突出"],["申报材料","申报表、承诺书、相关附件等","按要求准备电子版/纸质版","按官方要求提交"]].map(r=><tr key={r[0]}>{r.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table><div className={s.materialArt}><Image src="/media/reference-v4/hd/activity-materials-hd.png" alt="科创活动材料：模型与工具" width={1536} height={1024}/></div></div></section>
  <section><h2>从课程作品到活动表达</h2><div className={s.steps}><Image src="/media/reference-v4/hd/activity-expression-flow.svg" alt="从选择主题、完善作品、整理证据、反复演练到现场表达" width={1700} height={300}/></div></section>
  <section><h2>真实的实践现场</h2><div className={s.practice}>{practices.map(x=><figure key={x.t}><Image src={`/media/site-v3/activities/${x.src}`} alt={x.t} width={1536} height={1024}/><figcaption>{x.t}</figcaption></figure>)}</div><p className={s.tip}><BookOpen/>温馨提示：时间依据科瑞特手册所列申报周期整理，具体日期与要求以赛事当年官方通知为准。</p></section>
  <section className={s.cta}><MessagesSquare/><div><h2>活动咨询</h2><p>了解活动详情、材料准备与参与建议</p></div><a href="tel:19921536568">☎ 19921536568</a><span className={s.supports}>{["专业指导","材料梳理","全程支持"].map(x=><b key={x}><CheckCircle2/>{x}</b>)}</span></section>
</main>}
